application:
  bindAddress: :8446
  production: false
  debug: false
database:
  address: localhost:3402
  name: collector
  username: tradalia
  password: tradalia
authentication:
  authority: https://tradalia-server:8443/auth/realms/tradalia
  clientId: tradalia-backend
  clientSecret: YdImL2TpOb120tnerwsmLVJv6F3nHv0o
platform:
  system: https://tradalia-server:8449/api/system
messaging:
  address: localhost:8450
  username: rabbit-admin
  password: rabbit.admin
datastore:
  address: localhost:3410
  name: datastore
  username: tradalia
  password: tradalia
  staging:  staging
